import biography from './biography.json';
export { biography };
export const chapters = [
  { id: 'origin', number: '01', spine: 'ORIGIN', title: 'Learning to see', cover: ['YI KAI', 'ORIGIN'], subtitle: '1966–1979', color: '#E7D9BE', ink: '#292720', material: 'paper', height: 490, width: 122, excerpt: 'During those years, drawing was his only pleasure outside of work.', paragraphs: [2, 3, 4], notes: ['An interrupted education', 'Nine years in the Railway Corps', 'Drawing from observation'] },
  { id: 'study', number: '02', spine: 'STUDY', title: 'A life of study', cover: ['STUDY', 'PAINTING'], subtitle: '1979–1988', color: '#B9C4C6', ink: '#282D2D', material: 'paper', height: 512, width: 173, excerpt: 'Understanding ideas and concepts is far more important than the blind imitation of technique.', paragraphs: [5, 6], notes: ['Chinese painting', 'Oil painting', 'Art and education'] },
  { id: 'crossing', number: '03', spine: 'CROSSING', title: 'Beginning again', cover: ['CROSSING', 'SAN FRANCISCO'], subtitle: 'MARCH 11, 1990', color: '#F0E9D9', ink: '#183F72', material: 'vellum', height: 478, width: 108, excerpt: 'He began again entirely from scratch, relying on his own determination and resourcefulness.', paragraphs: [7, 8], notes: ['A visiting scholar', 'San Francisco, 1990', 'An independent life'] },
  { id: 'dialogue', number: '04', spine: 'DIALOGUE', title: 'Between cultures', cover: ['DIALOGUE', 'CHINA ↔ AMERICA'], subtitle: 'YI KAI', color: '#183F72', ink: '#F3EADB', material: 'cloth', height: 610, width: 286, excerpt: 'No single cultural tradition can meet the needs of humanity as a whole.', paragraphs: [9, 10, 11, 12, 13, 14, 15, 16, 17], notes: ['Culture as a way of life', 'Learning across traditions', 'Creating something new'] },
  { id: 'hand', number: '05', spine: 'HAND', title: 'The human hand', cover: ['PAINTING', 'THE HUMAN HAND'], subtitle: 'YI KAI', color: '#26231F', ink: '#F3EADB', material: 'cloth', height: 552, width: 156, excerpt: 'Painting is not dead, and painting must remain rooted in the human hand.', paragraphs: [18, 19, 20, 21, 26], notes: ['Mind and intellect', 'Body, eye, and hand', 'A lifelong discipline'] },
  { id: 'unresolved', number: '06', spine: 'UNRESOLVED', title: 'Leaving room for the unknown', cover: ['20–30%', 'LEFT OPEN'], subtitle: 'AN ONGOING PRACTICE', color: '#D9D6CE', ink: '#282720', material: 'vellum', height: 491, width: 165, excerpt: 'He deliberately leaves approximately twenty to thirty percent unresolved.', paragraphs: [22, 23, 24, 25, 27, 28, 29], notes: ['Exploration', 'Revision', 'Transformation'] },
  { id: 'index', number: '07', spine: 'INDEX', title: 'Selected works', cover: ['SELECTED', 'WORKS'], subtitle: '113 WORKS / SIX COLLECTIONS', color: '#7C8569', ink: '#161A11', material: 'paper', height: 324, width: 68, excerpt: 'What he has experienced, what he has thought, and what he has painted.', paragraphs: [], notes: ['Six collections', '113 works', 'A life in painting'] },
] as const;
export type Chapter = typeof chapters[number];
