// Text and career records supplied by the artist for this website.
export const collectingIntroduction = 'Yi Kai’s art is collected by many famous and successful individuals, museums, galleries, universities, corporations, luxury hotels all over the globe. His collectors include the Rockefeller family, Tung Chee-hwa’s family, and many other executives, politicians, doctors, professors, entrepreneurs/founders and business/community leaders.';
export const artistStatement = [
 'As a multi-disciplinary artist, my work is deeply informed by the juxtaposition of my 34 years in China and the 36 years I have spent in the United States. This unique life journey has shaped my perspective and provides a rich tapestry from which I draw inspiration.',
 'Through the mediums of paint, ink, and found objects, I explore the intricate concepts of humanity, reflecting on my immigration experience and the myriad of emotions intertwined within it. My artistic journey began in 1975, and over the decades, drawing and painting have become my primary means of self-discovery and understanding the world around me.',
 'The creative process for me is not a linear path; it is characterized by continuous revision, negation, and refinement. Each work evolves, reflecting my thoughts and feelings as they shift and change. This process enriches my art and provides me with profound intellectual and spiritual fulfillment. I invite viewers to engage with my work and join me in a dialogue about the human experience, shaped by diverse backgrounds and shared narratives. Through my art, I seek to bridge cultures and foster connection, illuminating the beauty and complexity of our shared humanity.'
];
export const careerSections = [
 {id:'special-collections',title:'Special Collections',items:[
 'Pomona College, Claremont, CA',
 'University St Thomas, St Paul, MN',
 'Hearts On Fire, Boston, MA',
 'Warwick Hotel, Paris, France',
 'The Minneapolis Institute of Art, MN',
 'Medtronic, Minneapolis, MN',
 'Key Investment, Minneapolis, MN',
 'Hang Seng Bank, Hong Kong',
 'SAP American, Philadelphia, PA',
 'LeeFon Corporation, Singapore',
 'The Woman’s Club of Minneapolis, MN',
 'Dorsey & Whitney, Hong Kong Office',
 'Minnesota Museum of American Arts, Minneapolis, MN',
 'Dolly Fiterman Fine Arts, Minneapolis, MN',
 'Piper Jaffray, Minneapolis, MN',
 'The St Paul Company, Minneapolis, MN',
 'China Times Newspaper, Taipei, China',
 'Museum of Fu Tan Po, Osaka, Japan',
 'Beijing Art Institute, China'
 ]},
 {id:'group-exhibitions',title:'Group Exhibitions',items:[
 '2023 Mirror Garden Art Museum, Tianjin, China',
 '2023 ATTN Art Gallery, Guangzhou, China',
 '2021 Featured Artist, Itsliquid, Italy',
 '2021 Chan Gallery, Pomona College, Claremont, CA',
 '2020 Artist of the Month, Itsliquid, Italy',
 '2018 Art Museum of Tianjin Academy of Fine Art, P.R of China',
 '2018 Three-man show in Alisan Fine Arts, Hong Kong',
 '2015 Alisan Fine Arts 35 years group show, Hong Kong',
 '2012 Los Angeles International Art Expo, Los Angeles, CA',
 '2011 George Cuttress Fine Arts, CA',
 '2011 University of St Thomas Gallery, Minneapolis, MN',
 '2011 Faster Gallery, University of Wisconsin, WI',
 '2010 San Francisco International Art Expo, San Francisco, CA',
 '2010 OCCOA Gallery, Orange County, CA',
 '2007 Brand 36 works on paper, Glendale, CA',
 '2005 Powers Gallery, Acton, MA',
 '2004 Powers Gallery, Acton, MA',
 '2003 New American Drawing 2003”, Santa Fe, NM',
 '2002 Plains Art Museum, Fargo, ND'
 ]},
 {id:'solo-exhibitions',title:'Solo Exhibitions',items:[
 '2020 The Progress Gallery, CA',
 '2015 Claremont Graduate University Gallery, Claremont, CA',
 '2015 53 Art Museum, Guangzhou, China',
 '2015 Alisan Fine Arts, Hong Kong',
 '2014 Museum of Art and History, Lancaster, CA',
 '2004 DeCordova Museum of Arts, Lincoln, MA',
 '2003 Gallery Lasietique, Scottsdale, AZ',
 '2000 Alison Fine Arts, Hong Kong',
 '2000 Museum West Fine Arts, San Francisco & Palo Alto, CA',
 '1999 Dolly Fiterman Fine Arts, Minneapolis, MN',
 '1998 Museum West Fine Arts, San Francisco, CA',
 '1998 Dai Ichi Fine Arts, New York',
 '1998 Alisan Fine Arts, Hong Kong',
 '1997 Nelson/ Rovzar Gallery, Seattle, WA',
 '1997 Orchard Point Exhibition Hall, Singapore',
 '1996 Nelson/ Rovzar Gallery, Seattle, WA',
 '1991 Asian Fine Arts, Minneapolis, MN',
 '1990 Larson Gallery, University of Minnesota, MN',
 '1989 Crown Art Gallery, Taipei, Taiwan',
 '1988 National Art Museum of the Peoples Republic of China, Beijing'
 ]},
 {id:'awards',title:'Awards',items:[
 '2020 Artist of the Month, Itsliquid, Italy',
 '2002 Best of the Show, 6th International Art Competition, Estes Park, CO',
 '2000 Work included in lecture by Elizabeth Brown, Director of National Museum of American Art,',
 '1996 Curator’s Choice, Auction, Minneapolis College of Art and Design, Minneapolis, MN',
 '1985 Award of Excellence, Beijing Art Exhibition, Beijing, China',
 '1981 Two Bronze Medals, National Art Exhibition of China, Beijing, China'
 ]},
 {id:'publications',title:'Publications',items:[
 '2015 What Goes Around Goes Around Yi Kai’s (catalogue)',
 '2013 Impression of US (catalogue)',
 '2005 Impression Ink Drawing of Tibet (catalogue)',
 '2001 5 paintings were published by Grand Image and distributed by Bruce McGraw, New York,',
 '2001 Time, Yin & Yang (catalogue), Alison Fine Arts, Hong Kong',
 '2001 New Paintings by Yi Kai (catalogue), Museum West Fine Arts, CA, USA',
 '1999 A Decade of paintings by Yi Kai (catalogue), Dolly Fiterman Fine Arts, Minneapolis, MN',
 '1997 Painting Album of Yi Kai (catalogue), Dynasties Art Gallery, Singapore Collection',
 '1989 Painting of Yi Kai (catalogue), Crown Art, Taipei'
 ]},
 {id:'teaching',title:'Teaching',items:[
 '2017 – 2020 Working as faculty member in Claremont Graduate University, CA',
 '1988 – 1990 Associate Professor, Central University of Nationalities, Beijing, China',
 '1983 – 1985 Assistant Professor, Art Institute of the People’s Liberation Army, Beijing, China',
 '2021 Chan Gallery, Pomona College, Claremont, CA',
 '2019 Guangzhou Academy of Fine Arts, China',
 '2018 Tianjin Academy of Fine Art, P.R of China',
 '2016 Claremont Graduate University, CA',
 '2015 53 Art Museum, Guangzhou, China,',
 '2015 Alisan Fine Arts, Hong Kong',
 '2017 Art lecture tour in 4 colleges in China',
 '2014 Art lecture tour in 6 colleges in China',
 '2013 Art lecture tour in 9 colleges in China',
 '2010 University of Santa Barbara, CA',
 '2008 University of Minnesota, MN',
 '2002 University of St Thomas, Minneapolis, MN',
 '1997 University of Singapore, Singapore',
 '1991 University of Minnesota, St Paul, MN'
 ]}
];
